
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_LLAVED = 16;
  public static final int TK_LISTA_SIMBOLOS = 24;
  public static final int TK_COM_MTL = 22;
  public static final int TK_CADENA = 17;
  public static final int TK_DIGIT = 3;
  public static final int TK_PC = 7;
  public static final int TK_CONJUNTO = 23;
  public static final int TK_SIMBOLOS = 20;
  public static final int TK_LETTERS = 4;
  public static final int TK_DOS_P = 19;
  public static final int TK_V = 13;
  public static final int EOF = 0;
  public static final int TK_P = 12;
  public static final int TK_CP = 8;
  public static final int TK_LLAVEIZ = 15;
  public static final int TK_OR = 10;
  public static final int TK_DPORCENTAJE = 5;
  public static final int error = 1;
  public static final int TK_CK = 9;
  public static final int TK_I = 11;
  public static final int TK_ASIGNACION = 18;
  public static final int TK_COMENT = 21;
  public static final int TK_CONJ = 2;
  public static final int TK_ID = 6;
  public static final int TK_ESPECIALES = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK_CONJ",
  "TK_DIGIT",
  "TK_LETTERS",
  "TK_DPORCENTAJE",
  "TK_ID",
  "TK_PC",
  "TK_CP",
  "TK_CK",
  "TK_OR",
  "TK_I",
  "TK_P",
  "TK_V",
  "TK_ESPECIALES",
  "TK_LLAVEIZ",
  "TK_LLAVED",
  "TK_CADENA",
  "TK_ASIGNACION",
  "TK_DOS_P",
  "TK_SIMBOLOS",
  "TK_COMENT",
  "TK_COM_MTL",
  "TK_CONJUNTO",
  "TK_LISTA_SIMBOLOS"
  };
}

